# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAbrirdocumentosnolidos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_abrirdocumentosnolidos(self):
    # Test name: abrir documentos não lidos
    # Step # | name | target | value | comment
    # 1 | open | /pje/Painel/painel_usuario/list.seam |  | 
    self.driver.get("https://pje.tjdft.jus.br/pje/Painel/painel_usuario/list.seam")
    # 2 | setWindowSize | 1936x1048 |  | 
    self.driver.set_window_size(1936, 1048)
    # 3 | mouseDown | css=#naoSegredoForm\3AidTarefaTree\3Aj__id249\3A 25\3A\3Aj_id250\3Atext > b |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#naoSegredoForm\\3AidTarefaTree\\3Aj__id249\\3A 25\\3A\\3Aj_id250\\3Atext > b")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseUp | css=.ajax-loader:nth-child(1) .rich-mp-container |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".ajax-loader:nth-child(1) .rich-mp-container")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 5 | click | css=body |  | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 6 | mouseOver | css=#naoSegredoForm\3AidTarefaTree\3Aj__id249\3A 25\3A\3Aj_id250\3Atext > .text-muted |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#naoSegredoForm\\3AidTarefaTree\\3Aj__id249\\3A 25\\3A\\3Aj_id250\\3Atext > .text-muted")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | css=#naoSegredoForm\3AidTarefaTree\3Aj__id249\3A 25\3A\3Aj_id250\3Atext > .text-muted |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | mouseOver | css=#naoSegredoForm\3AidTarefaTree\3Aj__id249\3A 25\3A\3Aj_id250\3Aicon > .rich-tree-h-ic-img |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#naoSegredoForm\\3AidTarefaTree\\3Aj__id249\\3A 25\\3A\\3Aj_id250\\3Aicon > .rich-tree-h-ic-img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseOut | css=#naoSegredoForm\3AidTarefaTree\3Aj__id249\3A 25\3A\3Aj_id250\3Aicon > .rich-tree-h-ic-img |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 10 | mouseOver | id=naoSegredoForm:idTarefaTree:j__id249:25::j_id250:handles |  | 
    element = self.driver.find_element(By.ID, "naoSegredoForm:idTarefaTree:j__id249:25::j_id250:handles")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | mouseOut | id=naoSegredoForm:idTarefaTree:j__id249:25::j_id250:handles |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 12 | click | id=naoSegredoForm:idTarefaTree:j__id249:25::j_id250:handle:img:collapsed |  | 
    self.driver.find_element(By.ID, "naoSegredoForm:idTarefaTree:j__id249:25::j_id250:handle:img:collapsed").click()
    # 13 | mouseOver | css=#naoSegredoForm\3AidTarefaTree\3Aj__id249\3A 25\3A\3Aj_id250\3Atext > b |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#naoSegredoForm\\3AidTarefaTree\\3Aj__id249\\3A 25\\3A\\3Aj_id250\\3Atext > b")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | mouseOut | css=#naoSegredoForm\3AidTarefaTree\3Aj__id249\3A 25\3A\3Aj_id250\3Atext > b |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | click | css=#consultaProcessoGridList\3A 0\3Aj_id283\3AtoolbarDiv\3Aj_id289 > .fa |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 16 | selectWindow | handle=${win6249} |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#consultaProcessoGridList\\3A 0\\3Aj_id283\\3AtoolbarDiv\\3Aj_id289 > .fa").click()
    self.vars["win6249"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6249"])
  
